// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujzdfucodaybadzrboea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqemRmdWNvZGF5YmFkenJib2VhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MzI5ODQsImV4cCI6MjA2NDMwODk4NH0.rbHIGzbuHDLXA7zrUOD-wua54-h89feziRgk0iQIxug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);